config/routes.rb
Rails.application.routes.draw do

  get 'rooms/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users

  get "search"=>"searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "relationship/index_follow"=>"relationships#index_follow"
    get "relationship/index_follower"=>"relationships#index_follower"
    get "search"=>"users#search"
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

  resources :groups, only: [:create, :index, :show, :new]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :book_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_many :group_user, dependent: :destroy
  has_many :group, through: :group_user

  has_one_attached :profile_image


  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end



  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def followings?(user)
    followings.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:top]
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new


    @today_book =  @books.created_today
    @yesterday_book = @books.created_yesterday
    @two_days_ago_book = @books.created_two_days_ago
    @three_days_ago_book = @books.created_three_days_ago
    @four_days_ago_book = @books.created_four_days_ago
    @five_days_ago_book = @books.created_five_days_ago
    @six_days_ago_book = @books.created_six_days_ago
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week

  
    if params[:created_at] == ""
      @search_book = "日付を選択してください"#①
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count#②
    end
    

    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = @user.books.includes(:favorites).sort_by {|x| x.favorites.where(created_at: from...to).size}.reverse


    @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_entry.each do |current|
        @another_entry.each do |another|
          if current.room_id == another.room_id
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      unless @is_room == true
        @room = Room.new
        @entry = Entry.new
      end
    end



  end
  
    def search
    @user = User.find(params[:user_id])
    @books = @user.books 
    if params[:created_at] == ""
      @search_book = "日付を選択してください"#①
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count#②
    end
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new


  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_books_rate.html.erb
      <h2>投稿数の前日比・前週比</h2>

    <table class="table table-bordered">
      <tr>
        <td>今日の投稿数</td>
        <td>前日の投稿数</td>
        <td>前日比</td>
      </tr>
      <tr>
        <td><%= today_book.count %></td>
        <td><%= yesterday_book.count %></td>
        <% if yesterday_book.count == 0 %>
          <td></td>
        <% else %>
        <td>
        <%= number_to_percentage(( (today_book.count) / (yesterday_book.count).to_f)*100, precision: 0) %></td>
        <% end %>
      </tr>
    </table>
    <table class="table table-bordered">
      <tr>
        <td>今週の投稿数</td>
        <td>前週の投稿数</td>
        <td>前週比</td>
      </tr>
      <tr>
        <td><%= this_week_book.count %></td>
        <td><%= last_week_book.count %></td>
        <% if last_week_book.count == 0 %>
          <td></td>
        <% else %>
        <td>
        <%= number_to_percentage(( (this_week_book.count) / (last_week_book.count).to_f)*100, precision: 0) %></td>
        <% end %>
      </tr>
    </table>

app/views/users/_books_week.html.erb
      <h2>7日分の投稿数</h2>

    <table class="table table-bordered">
      <tr>
        <td>6日前</td>
        <td>5日前</td>
        <td>4日前</td>
        <td>3日前</td>
        <td>2日前</td>
        <td>1日前</td>
        <td>今日</td>
      </tr>
      <tr>
        <td><%= six_days_ago_book.count %></td>
        <td><%= five_days_ago_book.count %></td>
        <td><%= four_days_ago_book.count %></td>
        <td><%= three_days_ago_book.count %></td>
        <td><%= two_days_ago_book.count %></td>
        <td><%= yesterday_book.count %></td>
        <td><%= today_book.count %></td>

      </tr>
    </table>
<div>
  <canvas id="myChart"></canvas>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count%></td>
        <td>フォロワー数：<%= user.followers.count%></td>

        <td>
          <% if current_user != user %>
            <% if current_user.followings?(user)%>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
        <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to user_relationship_index_follow_path(user.id) do%>
        <%= user.followings.count%>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to user_relationship_index_follower_path(user.id) do%>
        <%= user.followers.count%>
      <% end %>
    </th>

  </tr>
</table>

<div class='row'>
  <% if user == current_user%>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% else %>
    <% if current_user.followings?(user)%>
      <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn btn-info"%>

      <% if user.followings?(current_user)%>
        <% if @is_room %>
          <%= link_to 'chatを始める', room_path(@room_id) %>
        <% else %>
          <%= form_with model: @room do |f| %>
            <%= fields_for @entry do |e| %>
              <%= e.hidden_field :user_id, value: @user.id %>
            <% end %>
            <%= f.submit 'chatを始める' %>
          <% end %>
        <% end %>
      <% end %>


    <% else %>
      <%= link_to 'フォローする', user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
    <% end %>


  <% end %>

</div>

app/views/users/_search_books.html.erb
<table class="table table-bordered">
  <h4>検索結果</h4>
  <tr>
    <th>
        投稿数
    </th>
  </tr>
  <tr>
    <td>
      <%= search_book %>
    </td>
  </tr>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %>
      |
      <%= link_to "グループ一覧", groups_path %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
  $('#search_result').html("<%= j(render 'search_books', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>

      <%= render 'books_rate', today_book: @today_book, yesterday_book: @yesterday_book, this_week_book: @this_week_book, last_week_book: @last_week_book%>
      <%= render 'books_week', today_book: @today_book, yesterday_book: @yesterday_book, two_days_ago_book: @two_days_ago_book, three_days_ago_book: @three_days_ago_book, four_days_ago_book: @four_days_ago_book, five_days_ago_book: @five_days_ago_book, six_days_ago_book: @six_days_ago_book%>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
  let today_book = '<%== JSON.dump(@today_book.count)%>'
  let yesterday_book = '<%== JSON.dump(@yesterday_book.count)%>'
  let two_days_ago_book = '<%== JSON.dump(@two_days_ago_book.count)%>'
  let three_days_ago_book = '<%== JSON.dump(@three_days_ago_book.count)%>'
  let four_days_ago_book = '<%== JSON.dump(@four_days_ago_book.count)%>'
  let five_days_ago_book = '<%== JSON.dump(@five_days_ago_book.count)%>'
  let six_days_ago_book = '<%== JSON.dump(@six_days_ago_book.count)%>'


  const ctx = document.getElementById('myChart');

  new Chart(ctx, {
    type: 'line',
    data: {
      labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
      datasets: [{
        label: '投稿した本の数',
        data: [six_days_ago_book, five_days_ago_book, four_days_ago_book, three_days_ago_book, two_days_ago_book, yesterday_book, today_book],
        borderWidth: 3,
        borderColor: 'rgba(0,0,255,0.5)',
        tension: 0.4,


      }]
    },
    options: {
      scales: {
        y: {
          beginAtZero: true,
          max: 10

        }

      }
    }
  });
</script>

      <%= form_with url:user_search_path(params[:id]), method: :get, local: false do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit "検索",class: "btn btn-primary"%>

      <% end %>
      <div id="search_result">

      </div>
    </div>
  </div>
</div>